set(OBOL_RENDER_SCENARIO_SOURCES
    ${PROJECT_SOURCE_DIR}/tests/cad/test_cad_subpixel_proxy.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_arb_shader_parameters.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_arb8_draggers.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_arb8_edit_cycle.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_basic_context.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_bbox_action.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_callback_action.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_callback_action_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_callback_node.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_camera_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_draggers.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_embree.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_engine_converter.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_engine_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_event_callback_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_event_propagation.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_ext_selection.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_ext_selection_events.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_field_connections.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_glrender_action_modes.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_glrender_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_hud_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_hud_nanort.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_image_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_light_manips.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_lod_picking.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_manip_sequences.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_material_binding.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_nanort.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_nanort_shadow.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_nodekit_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_offscreen.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_offscreen_advanced.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_path_operations.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_pick_filter.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_pick_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_procedural_shape.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_quad_mesh_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_quad_viewport.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_quad_viewport_lod.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_raypick_shapes.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_render_manager_full.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_rt_proxy_shapes.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_scene_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_search_action.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_selection_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_sensor_interaction.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_sensors_rendering.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_shader_program.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_shadow_advanced.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_simple_draggers.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_sogl_bindings.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_text3_parts.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_view_volume_ops.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_viewport.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_write_read_action.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/stt_iosevka.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/stt_reference.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/test_shadow_direct.cpp)
