set(OBOL_CORE_UNIT_SOURCES
    ${PROJECT_SOURCE_DIR}/tests/unit/base_math_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/base_geometry_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/base_utilities_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/base_value_types_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/draggers_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/engines_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/error_handling_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/events_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/fields_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/image_assertions_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/image_fields_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/image_format_registry_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/interaction_kit_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/nodes_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/nanort_context_manager_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/projectors_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/scene_graph_structure_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/unit/sensors_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/tools/test_tools_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/cad/test_cad_ids.cpp
    ${PROJECT_SOURCE_DIR}/tests/threads/test_threads.cpp)

set(OBOL_DOMAIN_UNIT_SOURCES
    ${PROJECT_SOURCE_DIR}/tests/actions/test_actions_extended.cpp
    ${PROJECT_SOURCE_DIR}/tests/actions/test_actions_pick.cpp
    ${PROJECT_SOURCE_DIR}/tests/actions/test_actions_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/actions/test_glrender_action.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_base_advanced.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_base_extras.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_sb_matrix_box.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_sb_plist.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_sb_rotation_plane.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_sb_types.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_sb_viewvolume.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_sbdpmatrix_full.cpp
    ${PROJECT_SOURCE_DIR}/tests/base/test_sbtime_sbdict.cpp
    ${PROJECT_SOURCE_DIR}/tests/bundles/test_bundles_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/caches/test_caches_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/details/test_details_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/details/test_details_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/draggers/test_dragger_sequences.cpp
    ${PROJECT_SOURCE_DIR}/tests/draggers/test_draggers.cpp
    ${PROJECT_SOURCE_DIR}/tests/elements/test_elements_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/engines/test_engines_advanced.cpp
    ${PROJECT_SOURCE_DIR}/tests/engines/test_engines_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/engines/test_engines_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/engines/test_engines_suite2.cpp
    ${PROJECT_SOURCE_DIR}/tests/errors/test_errors_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/events/test_events_deeper.cpp
    ${PROJECT_SOURCE_DIR}/tests/events/test_events_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/fields/test_field_advanced.cpp
    ${PROJECT_SOURCE_DIR}/tests/fields/test_field_connections.cpp
    ${PROJECT_SOURCE_DIR}/tests/fields/test_field_containers.cpp
    ${PROJECT_SOURCE_DIR}/tests/fields/test_field_extras.cpp
    ${PROJECT_SOURCE_DIR}/tests/fields/test_mf_fields.cpp
    ${PROJECT_SOURCE_DIR}/tests/fields/test_sf_fields.cpp
    ${PROJECT_SOURCE_DIR}/tests/io/test_io_edge_cases.cpp
    ${PROJECT_SOURCE_DIR}/tests/io/test_io_file_ops.cpp
    ${PROJECT_SOURCE_DIR}/tests/io/test_io_input_binary.cpp
    ${PROJECT_SOURCE_DIR}/tests/io/test_io_write_action.cpp
    ${PROJECT_SOURCE_DIR}/tests/io/test_sodb.cpp
    ${PROJECT_SOURCE_DIR}/tests/lists/test_lists_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/manips/test_manips.cpp
    ${PROJECT_SOURCE_DIR}/tests/manips/test_manips_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/misc/test_misc_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/misc/test_proto.cpp
    ${PROJECT_SOURCE_DIR}/tests/misc/test_scene_manager.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodekit_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodekit_traversal.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodes_anim_misc.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodes_extended.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodes_geometry.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodes_misc.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodes_path.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodes_shape_ext.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_nodes_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_procedural_shape.cpp
    ${PROJECT_SOURCE_DIR}/tests/nodes/test_selection_nodes.cpp
    ${PROJECT_SOURCE_DIR}/tests/profiler/test_profiler_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/projectors/test_projectors_deep.cpp
    ${PROJECT_SOURCE_DIR}/tests/projectors/test_projectors_suite.cpp
    ${PROJECT_SOURCE_DIR}/tests/sensors/test_sensors_deeper.cpp
    ${PROJECT_SOURCE_DIR}/tests/sensors/test_sensors_extra.cpp
    ${PROJECT_SOURCE_DIR}/tests/sensors/test_sensors_suite.cpp)

set(OBOL_UNIT_SOURCES
    ${OBOL_CORE_UNIT_SOURCES}
    ${OBOL_DOMAIN_UNIT_SOURCES})
