set(OBOL_PORTABLE_RENDER_SOURCES
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_fixture_smoke_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/offscreen_renderer_api_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_semantic_contracts_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/interaction_contracts_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/portable_feature_contracts_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/demo_catalogue_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/subtexture_render_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/visual_regression_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_lighting.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_cameras.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_colored_cube.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_coordinates.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_indexed_face_set.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_point_set.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_quad_mesh.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_indexed_line_set.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_face_set.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_line_set.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_triangle_strip_set.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_vertex_colors.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_marker_set.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_image_node.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_sphere_position.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_reset_transform.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_switch_visibility.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_drawstyle.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_lod.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_text3.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_texture.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_hud_overlay.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_text2.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_hud_no3d.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_hud_demo.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_scene.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_cubemap.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_gl_big_image.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_multi_texture.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_transparency.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_ascii_text.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_annotation.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_array_multiple_copy.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_checker_texture.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_clip_plane.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_shadow.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_gradient.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_background_gradient.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_iosevka_text2.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_iosevka_text3.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_text_demo.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_sorender_manager.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_gl_features.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_texture3.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_bump_map.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_environment.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_alpha_test.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_texture_transform.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_depth_buffer.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_shape_hints.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_viewport_scene.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_scene_texture.cpp
    ${PROJECT_SOURCE_DIR}/tests/rendering/render_scene_texture_multi_mgr.cpp
    ${PROJECT_SOURCE_DIR}/examples/demo_scenes/demo_scenes.cpp)
